image: docker:git
#image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - check-packages
  - build-and-deploy
  - git-push-to-mirror

check-packages job:
  stage: check-packages
  image: alpine:3.6
  script:
  - cat /etc/alpine-release
  - apk update
  - chmod +x checkpackages.sh
  - ./checkpackages.sh

build job:
  stage: build-and-deploy
  variables:
    DOCKERHUB_REGISTRY: "https://index.docker.io/v1/"
    DOCKER_REGISTRY_DOCKERHUB_REPO: "anacha/ng-testplat"
  only:
    - master
  script:
  - TMPTAG="6.0.3-alpine"
  - docker info
  #- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - >-
    docker build --pull 
    -t $CI_REGISTRY_IMAGE:$TMPTAG
    -t $CI_REGISTRY_IMAGE:latest
    -t $DOCKER_REGISTRY_DOCKERHUB_REPO:$TMPTAG
    -t $DOCKER_REGISTRY_DOCKERHUB_REPO:latest
    .
  - docker images
  - docker push $CI_REGISTRY_IMAGE:$TMPTAG
  - docker push $CI_REGISTRY_IMAGE:latest
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD $DOCKERHUB_REGISTRY
  - docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:$TMPTAG
  - docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:latest

.job_sshpushtemplate: &sshpush
  image: anacha/openssh-client
  before_script:
    - which ssh-agent || (apk add --no-cache --update openssh-client)
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - $([[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config) 
    # - ssh-keyscan -H 'bitbucket.org' >> ~/.ssh/known_hosts

Github Mirror:
  <<: *sshpush
  stage: git-push-to-mirror
  variables:
    GITHUB_REPO: "github.com:anacpe9/ng-testplat.git"
  only:
    - master
  script:
    - echo "$GITHUB_SSH_PRIVATE_KEY" | ssh-add -
    - ssh-add -l
    - git push --mirror git@$GITHUB_REPO
    - git push git@$GITHUB_REPO HEAD:master

Bitbucket Mirror:
  <<: *sshpush
  stage: git-push-to-mirror
  variables:
    BITBUCKET_REPO: "bitbucket.org:anacpe9/ng-testplat.git"
  only:
    - master
  script:
    - echo "$BITBUCKET_SSH_PRIVATE_KEY" | ssh-add -
    - ssh-add -l
    - git push --mirror git@$BITBUCKET_REPO
    - git push git@$BITBUCKET_REPO HEAD:master
